name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install --with test
    - name: Build and Install
      run: |
        poetry build
        pip install .
    - name: Run pytest
      run: |
        poetry run pytest
